### ISSUE TITLE
Any tools that use this data yet?

### ISSUE THREAD

**Issue by shadow-light** [Copenhagen-Alliance/versification-specification#23]
I'm keen to use this data but wondering if anyone has created anything that can do automated conversion of a USX or USFM file yet?

I.e. Give it a USX/USFM file and output the same file but with the versification desired.

@jonathanrobie Do you know of anything? Otherwise I may write a script myself.

**Comment by jonathanrobie** [comment]
This is used in some alignment projects, but I do not know of a utility that changes the versification in a translation project unless it also converts all translations to a different format, e.g. one-line-per-verse in some GPT projects.

For any given translation, you should consider starting with the versification sniffer to guess what the real versification is - many translations do not use the standard versifications as is.   But you could test your code with a known translation that does conform.

Perhaps we can use email rather than issues for communication?
