### ISSUE TITLE
Problem with maxVerses and readability

### ISSUE THREAD

**Issue by jonathanrobie** [Copenhagen-Alliance/versification-specification#4]
I just spent some time talking to a UBS archivist, who told me hand-editability is essential, and they need to be able to easily see, for each entry in maxVerses, which chapter it corresponds to.

So instead of an array:

```javascript
    "maxVerses": {
        "GEN": [
            31,
            25,
            24,
            26,
            32,
            22,
            24,
            22,
            29,
            32,
```

She would prefer a dictionary that makes the chapter explicit so they can see what it corresponds to:

```javascript
    "maxVerses": {
        "GEN": {
            1: 31,
            2: 25,
            3: 24,
            4: 26,
            5: 32,
            6: 22,
            7: 24,
            8: 22,
            9: 29,
            10: 32,
```

That would be easy to do in Python, but [the JSON specification](https://www.json.org/json-en.html) has limitations that restrict our options:

1. Every key must be a string.
2. There are no comments.

Given these restrictions, the best I can think to do is not terribly elegant:

```javascript
    "maxVerses": {
        "GEN": {
            "1": 31,
            "2": 25,
            "3": 24,
            "4": 26,
            "5": 32,
            "6": 22,
            "7": 24,
            "8": 22,
            "9": 29,
            "10": 32,
            "11": 32,
```

Not terribly elegant, but it's the best I can think of if we want to explicitly represent the chapter and do this in pure JSON.

Thoughts?

**Comment by FoolRunning** [comment]
With the work that you are doing to use David's stuff to generate a versification file, I should think this file should never be hand-edited. I think the only reason they think hand-editability is essential is because that is what they are currently doing. I really don't want to make the file format more complicated/awkward if the only reason is that it is currently hand-edited. JSON is not designed to be hand-edited.
Worst-case, we need to create some UI that allows specifying the versification for a project.

**Comment by jonathanrobie** [comment]
Or we could always do a .vrs <--> .json conversion utility if we had to.
